### PR TITLE
fix(stacks): remove support for limit

### PR DESCRIPTION
**Pull request by mweibel**
BREAKING CHANGE: Removes possibility to supply limit/offset

### CODE REVIEW

**Comment by chregu** [comment]
You don't have to remove it, it's actually supported now (it wasn't before). 
Maybe just needs documentation that "offset" needs to be the value of the "cursor" returned. As explained here for sourceimages https://rokka.io/documentation/references/searching-images.html#deep-paging-beyond-10%2C000-hits (you just need it always for stacks and not only after 10'000 hits, but the mechanism is the same)

**Comment by mweibel** [comment]
Ah, right. But the limit isn't looked at, right?

**Comment by mweibel** [comment]
@chregu fixed

**Comment by mweibel** [comment]
actually fixed in https://github.com/rokka-io/rokka.js/commit/f1ca20607a8de44701a0fc8949622284a36e2042

was a misunderstanding :)

**Pull request closed without merging**
